ACTIVITIES = [
    "Running",
    "Cycling",
    "Walking",
    "Driving",
    "Office",
    "College",
    "Shopping",
    "Travel",
    "Photography",
    "Hiking",
    "Camping",
    "Dog Walking",
    "Gardening",
]